name             'junos-config'
maintainer       'Arne Sund'
maintainer_email 'git@arnesund.no'
license          'GPLv2'
description      'Push Juniper Configuration Changes using Chef'
long_description 'Push Juniper Configuration Changes using Chef'
version          '0.1.0'
