name             'chef-junos-config'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures chef-junos-config'
long_description 'Installs/Configures chef-junos-config'
version          '0.1.0'
